server.port=8080
spring.application.name=majorProject
spring.datasource.url=jdbc:mysql://localhost:3306/major1234
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
